# Generated by Django 4.2.16 on 2025-09-13 20:01

import billing.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_remove_plan_price_plan_theem_plan_database_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePaymentOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('orderID', models.CharField(default=billing.models.payOrderCodeGen, max_length=250, unique=True, verbose_name='Order ID')),
                ('order_secret', models.CharField(default=billing.models.payOrderSecretCodeGen, max_length=254, unique=True, verbose_name='Order Secret Code')),
                ('transactionNo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Transaction Number')),
                ('progress', models.CharField(choices=[('1', 'Pending'), ('2', 'Paid'), ('3', 'Completed'), ('4', 'Cancelled')], default='1', max_length=254, verbose_name='Order Progress')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.availableproject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Payment Order',
                'verbose_name_plural': 'Service Payment Orders',
                'ordering': ['-creation_date'],
            },
        ),
    ]
