# Generated by Django 4.2.16 on 2025-09-10 11:16

import billing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0006_rename_expires_at_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePaymentOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(default=billing.models.payOrderCodeGen, max_length=250, null=True, verbose_name='Order ID')),
                ('order_secret', models.CharField(default=billing.models.payOrderSecretCodeGen, max_length=254, null=True, verbose_name='Order Secret Code')),
                ('transactionNo', models.CharField(max_length=250, null=True, verbose_name='Transaction Number')),
                ('progress', models.CharField(choices=[('1', 'Pending'), ('2', 'Paid'), ('3', 'Complited'), ('4', 'Cancelled')], default='1', max_length=254, null=True, verbose_name='Order Progress')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='Creation Date')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
            options={
                'verbose_name': 'Service Payment Order Model',
                'verbose_name_plural': 'Service Payment Order Models',
            },
        ),
    ]
