# Generated by Django 4.2.16 on 2025-09-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_availableproject_media_folder_path'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepaymentordermodel',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.availableproject'),
        ),
    ]
