# Generated by Django 4.2.16 on 2025-09-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_alter_deploymentcontainerenvvar_unique_together'),
        ('projects', '0005_envvarstitle_project_container_and_more'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepaymentordermodel',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='deployments.deployment'),
        ),
        migrations.AddField(
            model_name='servicepaymentordermodel',
            name='order_type',
            field=models.CharField(choices=[('1', 'Buy'), ('2', 'Renew'), ('3', 'Upgrade')], default='1', max_length=254, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.availableproject'),
        ),
    ]
