# Generated by Django 4.2.16 on 2025-09-10 12:10

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_servicepaymentordermodel_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepaymentordermodel',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Service Payment Order', 'verbose_name_plural': 'Service Payment Orders'},
        ),
        migrations.AddField(
            model_name='servicepaymentordermodel',
            name='duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='orderID',
            field=models.CharField(default=billing.models.payOrderCodeGen, max_length=250, unique=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='order_secret',
            field=models.CharField(default=billing.models.payOrderSecretCodeGen, max_length=254, unique=True, verbose_name='Order Secret Code'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='progress',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Paid'), ('3', 'Completed'), ('4', 'Cancelled')], default='1', max_length=254, verbose_name='Order Progress'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='transactionNo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Transaction Number'),
        ),
    ]
