# Generated by Django 4.2.16 on 2025-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_servicepaymentordermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepaymentordermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
