# Generated by Django 4.2.16 on 2025-09-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('command', models.TextField(help_text='اسم الدالة أو الأمر لتنفيذه عبر Docker')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AvailableProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('backfront', 'Backend&Frontend'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('redis', 'Redis')], max_length=20)),
                ('technology', models.CharField(blank=True, choices=[('django', 'Django'), ('node', 'Node.js'), ('laravel', 'Laravel'), ('php', 'PHP'), ('react', 'React'), ('vue', 'Vue.js')], max_length=50, null=True)),
                ('docker_image_name', models.CharField(max_length=200)),
                ('env_vars', models.JSONField(blank=True, default=dict, help_text='{deployment}, {this_container_domain}, {frontend_domain}, {backfront_domain}, {db_name}, {db_user}, {db_pass}, {db_container_name}')),
                ('default_port', models.PositiveIntegerField(blank=True, null=True)),
                ('volume', models.JSONField(blank=True, default=list, help_text='List of volume paths')),
                ('script_run_after_install', models.TextField(blank=True, help_text='{container.id}')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='projects.availableproject')),
            ],
        ),
        migrations.CreateModel(
            name='ActionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(help_text='الاسم الداخلي للاستخدام بالكود', max_length=50)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('int', 'Integer')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('default', models.CharField(blank=True, help_text='{deployment.id}', max_length=100, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='projects.action')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='container',
            field=models.ManyToManyField(related_name='actions', to='projects.projectcontainer'),
        ),
        migrations.CreateModel(
            name='EnvVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('is_secret', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, help_text='{container.deployment.id}', max_length=100)),
                ('project_container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_envs', to='projects.projectcontainer')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('project_container', 'key')},
            },
        ),
    ]
