# Generated by Django 4.2.16 on 2025-09-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('command', models.TextField(help_text='اسم الدالة أو الأمر لتنفيذه عبر Docker (مثلاً: change_admin_password)')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='AvailableProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('docker_image_name', models.CharField(max_length=100, null=True)),
                ('media_folder_path', models.CharField(default='media', max_length=100, null=True)),
                ('description', models.TextField()),
                ('folder', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
        migrations.CreateModel(
            name='ActionParameterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='الاسم المعروض للمستخدم', max_length=100, null=True)),
                ('name', models.CharField(help_text='الاسم الداخلي (للاستخدام في الكود/الـcommand)', max_length=50)),
                ('data_type', models.CharField(choices=[('string', 'string'), ('boolean', 'boolean'), ('int', 'integer')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('default', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='projects.actionmodel')),
            ],
        ),
        migrations.AddField(
            model_name='actionmodel',
            name='project',
            field=models.ManyToManyField(related_name='actions', to='projects.availableproject'),
        ),
        migrations.CreateModel(
            name='EnvVarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('is_secret', models.BooleanField(default=False, help_text='اخفاء')),
                ('required', models.BooleanField(default=False)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.availableproject')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
