# Generated by Django 4.2.16 on 2025-09-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='frontend_docker_image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='has_frontend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='has_redis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='redis_docker_image_name',
            field=models.CharField(blank=True, default='redis:7', max_length=100, null=True),
        ),
    ]
