# Generated by Django 4.2.16 on 2025-09-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='docker_image_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
