# Generated by Django 4.2.16 on 2025-09-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontainer',
            name='script_run_after_install',
            field=models.TextField(blank=True, help_text='{container.id}'),
        ),
    ]
