# Generated by Django 4.2.16 on 2025-09-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvVarsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='envvar',
            options={'ordering': ['sort_index']},
        ),
        migrations.AddField(
            model_name='envvar',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('int', 'Integer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='envvar',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='envvar',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_envs', to='projects.envvarstitle'),
        ),
    ]
