# Generated by Django 4.2.16 on 2025-09-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcontainer_script_run_after_install'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontainer',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict, help_text='{domain}, {deployment}, {db_name}, {db_user}, {db_pass}, {db_container_name}'),
        ),
    ]
