# Generated by Django 4.2.16 on 2025-09-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_availableproject_frontend_docker_image_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableproject',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='availableproject',
            name='media_folder_path',
        ),
        migrations.AddField(
            model_name='availableproject',
            name='redis_host_env_var_name',
            field=models.CharField(blank=True, default='REDIS_HOST', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='redis_port_env_var_name',
            field=models.CharField(blank=True, default='REDIS_PORT', max_length=100, null=True),
        ),
    ]
