# Generated by Django 4.2.16 on 2025-09-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_envvarstitle_alter_envvar_options_envvar_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envvar',
            name='project_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_envs', to='projects.projectcontainer'),
        ),
    ]
