# Generated by Django 4.2.16 on 2025-09-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_availableproject_docker_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='media_folder_path',
            field=models.CharField(default='media', max_length=100, null=True),
        ),
    ]
