# Generated by Django 4.2.16 on 2025-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectcontainer_env_vars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontainer',
            name='type',
            field=models.CharField(choices=[('backfront', 'Backend&Frontend'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('redis', 'Redis')], max_length=20),
        ),
    ]
