# Generated by Django 4.2.16 on 2025-09-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_envvar_project_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envvar',
            name='project_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_envs', to='projects.projectcontainer'),
        ),
        migrations.AlterField(
            model_name='envvar',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_envs', to='projects.envvarstitle'),
        ),
    ]
