# Generated by Django 4.2.16 on 2025-09-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_availableproject_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='db_engine_env_var_name',
            field=models.CharField(blank=True, default='DB_ENGINE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='db_host_env_var_name',
            field=models.CharField(blank=True, default='DB_HOST', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='db_name_env_var_name',
            field=models.CharField(blank=True, default='DB_NAME', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='db_password_env_var_name',
            field=models.CharField(blank=True, default='DB_PASSWORD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='db_port_env_var_name',
            field=models.CharField(blank=True, default='DB_PORT', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='db_user_env_var_name',
            field=models.CharField(blank=True, default='DB_USER', max_length=100, null=True),
        ),
    ]
