# Generated by Django 4.2.16 on 2025-09-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_availableproject_media_folder_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('command', models.CharField(help_text='اسم الدالة أو الأمر لتنفيذه عبر Docker (مثلاً: change_admin_password)', max_length=200)),
                ('project', models.ManyToManyField(related_name='actions', to='projects.availableproject')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='EnvVarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('is_secret', models.BooleanField(default=False, help_text='اخفاء')),
                ('project', models.ManyToManyField(related_name='envs', to='projects.availableproject')),
            ],
        ),
        migrations.CreateModel(
            name='ActionParameterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data_type', models.CharField(choices=[('string', 'string'), ('boolean', 'boolean'), ('int', 'integer')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('default', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='projects.actionmodel')),
            ],
        ),
    ]
