# Generated by Django 4.2.16 on 2025-09-18 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_envvar_project_container_alter_envvar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='envvarstitle',
            name='project_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_title_envs', to='projects.projectcontainer'),
        ),
        migrations.AlterUniqueTogether(
            name='envvar',
            unique_together={('title', 'key')},
        ),
        migrations.RemoveField(
            model_name='envvar',
            name='project_container',
        ),
    ]
