# Generated by Django 4.2.16 on 2025-09-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectcontainer_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='envvar',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='envvar',
            name='project_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectcontainer'),
        ),
        migrations.AlterUniqueTogether(
            name='envvar',
            unique_together={('project_container', 'key')},
        ),
        migrations.RemoveField(
            model_name='envvar',
            name='project',
        ),
    ]
