# Generated by Django 4.2.16 on 2025-09-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_actionmodel_envvarmodel_actionparametermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envvarmodel',
            options={'ordering': ['key']},
        ),
        migrations.AlterUniqueTogether(
            name='envvarmodel',
            unique_together={('project', 'key')},
        ),
        migrations.RemoveField(
            model_name='envvarmodel',
            name='project',
        ),
        migrations.AddField(
            model_name='envvarmodel',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.availableproject'),
        ),
    ]
