# Generated by Django 4.2.16 on 2025-09-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_availableproject_db_engine_env_var_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envvarmodel',
            name='default_value',
            field=models.CharField(blank=True, help_text='{self.deployment.id}', max_length=100),
        ),
    ]
