# Generated by Django 4.2.16 on 2025-09-16 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_envvar_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envvar',
            name='project_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_envs', to='projects.projectcontainer'),
        ),
    ]
