# Generated by Django 4.2.16 on 2025-09-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_envvarstitle_project_container_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envvar',
            options={'ordering': ['-sort_index']},
        ),
    ]
