# Generated by Django 4.2.16 on 2025-09-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_envvarmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionparametermodel',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
