# Generated by Django 4.2.16 on 2025-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_envvarmodel_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='script_run_after_install',
            field=models.TextField(blank=True, help_text='{deployment.id}'),
        ),
        migrations.AlterField(
            model_name='envvarmodel',
            name='default_value',
            field=models.CharField(blank=True, help_text='{deployment.id}', max_length=100),
        ),
    ]
