# Generated by Django 4.2.16 on 2025-09-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_actionparametermodel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionmodel',
            name='command',
            field=models.TextField(help_text='اسم الدالة أو الأمر لتنفيذه عبر Docker (مثلاً: change_admin_password)'),
        ),
        migrations.AlterField(
            model_name='actionparametermodel',
            name='label',
            field=models.CharField(blank=True, help_text='الاسم المعروض للمستخدم', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actionparametermodel',
            name='name',
            field=models.CharField(help_text='الاسم الداخلي (للاستخدام في الكود/الـcommand)', max_length=50),
        ),
    ]
