# Generated by Django 4.2.16 on 2025-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_envvar_project_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='project',
            field=models.ManyToManyField(related_name='actions', to='projects.projectcontainer'),
        ),
    ]
