# Generated by Django 4.2.16 on 2025-09-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_action_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='project',
            new_name='container',
        ),
    ]
