# Generated by Django 4.2.16 on 2025-09-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_actionmodel_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envvarmodel',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
