# Generated by Django 4.2.16 on 2025-09-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='availableproject',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', max_length=20, verbose_name='مستوى الصعوبة'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='disk_size_mb',
            field=models.PositiveIntegerField(default=500, verbose_name='الحجم المطلوب (MB)'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='install_time_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='زمن التثبيت المتوقع (بالدقائق)'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.category'),
        ),
    ]
