# Generated by Django 4.2.16 on 2025-09-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_project'),
        ('projects', '0008_category_availableproject_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='minimum_operating_requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan', verbose_name='ادنى متطلبات التشغيل'),
        ),
    ]
