# Generated by Django 4.2.16 on 2025-09-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_project_action_container'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='container',
            new_name='containerr',
        ),
    ]
