# Generated by Django 4.2.16 on 2025-09-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_availableproject_minimum_operating_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableproject',
            name='categories',
        ),
        migrations.AddField(
            model_name='projectcontainer',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('php', 'PHP'), ('java', 'Java'), ('csharp', 'C#'), ('go', 'Go'), ('ruby', 'Ruby')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectcontainer',
            name='technology',
            field=models.CharField(blank=True, choices=[('django', 'Django'), ('fastapi', 'FastAPI'), ('flask', 'Flask'), ('node', 'Node.js'), ('express', 'Express.js'), ('laravel', 'Laravel'), ('spring', 'Spring Boot'), ('dotnet', '.NET'), ('php', 'PHP (Raw)'), ('react', 'React'), ('vue', 'Vue.js'), ('angular', 'Angular'), ('svelte', 'Svelte')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectcontainer',
            name='type',
            field=models.CharField(choices=[('backfront', 'Backend & Frontend'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('redis', 'Redis'), ('db', 'Database'), ('worker', 'Worker / Celery'), ('proxy', 'Reverse Proxy')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
