# Generated by Django 4.2.16 on 2025-09-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_container_action_containerr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='containerr',
        ),
        migrations.AddField(
            model_name='action',
            name='container',
            field=models.ManyToManyField(related_name='actions', to='projects.projectcontainer'),
        ),
    ]
