# Generated by Django 4.2.16 on 2025-09-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_action_containerr_action_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionparameter',
            name='default',
            field=models.CharField(blank=True, help_text='{deployment.id}', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='envvar',
            name='default_value',
            field=models.CharField(blank=True, help_text='{container.deployment.id}', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectcontainer',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict, help_text='{deployment}, {this_container_domain}, {frontend_domain}, {backfront_domain}, {db_name}, {db_user}, {db_pass}, {db_container_name}'),
        ),
    ]
