# Generated by Django 4.2.16 on 2025-09-19 19:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_availableproject_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='install_steps',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
