# Generated by Django 4.2.16 on 2025-09-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_availableproject_install_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='installs',
            field=models.PositiveIntegerField(default=0, verbose_name='زمن التثبيت المتوقع (بالدقائق)'),
        ),
    ]
