# Generated by Django 4.2.16 on 2025-09-20 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_category_availableproject_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontainer',
            name='command',
            field=models.TextField(blank=True, help_text='الأمر الذي يُنفذ عند تشغيل الكونتينر', null=True),
        ),
        migrations.AddField(
            model_name='projectcontainer',
            name='entrypoint',
            field=models.TextField(blank=True, help_text='استبدال الـ Entrypoint الافتراضي للصورة', null=True),
        ),
        migrations.AddField(
            model_name='projectcontainer',
            name='labels',
            field=models.JSONField(blank=True, default=dict, help_text='Labels key:value metadata'),
        ),
        migrations.AddField(
            model_name='projectcontainer',
            name='networks',
            field=models.JSONField(blank=True, default=list, help_text='الشبكات التي سينضم إليها الكونتينر'),
        ),
        migrations.AddField(
            model_name='projectcontainer',
            name='ports',
            field=models.JSONField(blank=True, default=list, help_text="قائمة المنافذ لربط {host:container} مثل [{'8000':'80'}]"),
        ),
        migrations.AddField(
            model_name='projectcontainer',
            name='privileged',
            field=models.BooleanField(default=False, help_text='تشغيل الكونتينر بوضع Privileged (صلاحيات كاملة)'),
        ),
        migrations.AddField(
            model_name='projectcontainer',
            name='restart_policy',
            field=models.CharField(choices=[('no', 'No'), ('always', 'Always'), ('on-failure', 'On Failure'), ('unless-stopped', 'Unless Stopped')], default='unless-stopped', help_text='سياسة إعادة التشغيل للكونتينر', max_length=20),
        ),
        migrations.AddField(
            model_name='projectcontainer',
            name='working_dir',
            field=models.CharField(blank=True, help_text='الدليل الافتراضي الذي يبدأ فيه الكونتينر', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectcontainer',
            name='default_port',
            field=models.PositiveIntegerField(blank=True, help_text='المنفذ الافتراضي داخل الكونتينر', null=True),
        ),
        migrations.AlterField(
            model_name='projectcontainer',
            name='docker_image_name',
            field=models.CharField(help_text='اسم صورة Docker مثل: postgres:14 أو nginx:latest', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectcontainer',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict, help_text='قاموس المتغيرات البيئية {KEY: VALUE}'),
        ),
        migrations.AlterField(
            model_name='projectcontainer',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('php', 'PHP'), ('java', 'Java'), ('csharp', 'C#'), ('go', 'Go'), ('ruby', 'Ruby'), ('postgresql', 'PostgreSQL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectcontainer',
            name='project',
            field=models.ForeignKey(help_text='المشروع الذي ينتمي له هذا الكونتينر', on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='projects.availableproject'),
        ),
        migrations.AlterField(
            model_name='projectcontainer',
            name='script_run_after_install',
            field=models.TextField(blank=True, help_text='سكريبت يتم تنفيذه بعد تثبيت الكونتينر. يمكن أن يحتوي {container.id}'),
        ),
        migrations.AlterField(
            model_name='projectcontainer',
            name='volume',
            field=models.JSONField(blank=True, default=list, help_text='قائمة المجلدات المربوطة {host:container}'),
        ),
    ]
