# Generated by Django 4.2.16 on 2025-09-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectcontainer_command_projectcontainer_entrypoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontainer',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict, help_text='\n        يمكنك استخدام placeholders ديناميكية داخل القيم:\n        - الكونتينر الحالي: {container.container_name}, {container.domain}, {container.env.VAR_NAME}\n        - كونتينرات أخرى حسب النوع أو الاسم: {container.db.env.POSTGRES_USER}, {container.frontend.domain}\n        - Deployment والـ Plan: {container.deployment.id}, {container.deployment.plan.ram}, {container.deployment.plan.cpu}\n        - متغيرات عامة: {frontend_domain}, {backfront_domain}\n        مثال:\n        {\n            "DJANGO_ALLOWED_HOSTS": "{container.frontend.domain},127.0.0.1,localhost",\n            "DATABASE_URL": "postgres://{container.db.env.POSTGRES_USER}:{container.db.env.POSTGRES_PASSWORD}@{container.db.container_name}:5432/{container.db.env.POSTGRES_DB}"\n        }\n        '),
        ),
    ]
