# Generated by Django 4.2.16 on 2025-09-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_projectcontainer_env_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
