# Generated by Django 4.2.16 on 2025-09-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_availableproject_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableproject',
            name='installs',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد التثبيتات'),
        ),
    ]
