# Generated by Django 4.2.16 on 2025-09-22 18:06

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_project'),
        ('projects', '0017_alter_availableproject_installs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='action',
            name='label_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='action',
            name='label_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='action',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='action',
            name='label_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='action',
            name='label_ro',
            field=models.CharField(max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='actionparameter',
            name='label_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='actionparameter',
            name='label_de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='actionparameter',
            name='label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='actionparameter',
            name='label_he',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='actionparameter',
            name='label_ro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='envvar',
            name='label_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='envvar',
            name='label_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='envvar',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='envvar',
            name='label_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='envvar',
            name='label_ro',
            field=models.CharField(max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='envvarstitle',
            name='title_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='envvarstitle',
            name='title_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='envvarstitle',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='envvarstitle',
            name='title_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='envvarstitle',
            name='title_ro',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='action',
            name='command',
            field=models.TextField(help_text='The function name or command to execute via Docker', verbose_name='Command'),
        ),
        migrations.AlterField(
            model_name='action',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='actionparameter',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('int', 'Integer')], max_length=20, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='actionparameter',
            name='default',
            field=models.CharField(blank=True, help_text='{deployment.id}', max_length=100, null=True, verbose_name='Default Value'),
        ),
        migrations.AlterField(
            model_name='actionparameter',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='actionparameter',
            name='name',
            field=models.CharField(help_text='Internal name for code usage', max_length=50, verbose_name='Internal Name'),
        ),
        migrations.AlterField(
            model_name='actionparameter',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='Difficulty Level'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='disk_size_mb',
            field=models.PositiveIntegerField(default=500, verbose_name='Required Disk Size (MB)'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='install_steps',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Installation Steps'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='install_time_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='Estimated Install Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='installs',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Installs'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='minimum_operating_requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan', verbose_name='Minimum Operating Requirements'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='envvar',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('int', 'Integer')], max_length=20, null=True, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='envvar',
            name='default_value',
            field=models.CharField(blank=True, help_text='{container.deployment.id}', max_length=100, verbose_name='Default Value'),
        ),
        migrations.AlterField(
            model_name='envvar',
            name='is_secret',
            field=models.BooleanField(default=False, verbose_name='Is Secret'),
        ),
        migrations.AlterField(
            model_name='envvar',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='envvar',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='envvar',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='envvar',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Sort Index'),
        ),
        migrations.AlterField(
            model_name='envvarstitle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
