# Generated by Django 5.2.6 on 2025-09-22 19:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_category_options_action_label_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='about',
            field=tinymce.models.HTMLField(blank=True, verbose_name='About Project'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='about_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About Project'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='about_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About Project'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='about_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About Project'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='about_he',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About Project'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='about_ro',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About Project'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='install_steps_ar',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Installation Steps'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='install_steps_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Installation Steps'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='install_steps_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Installation Steps'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='install_steps_he',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Installation Steps'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='install_steps_ro',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Installation Steps'),
        ),
    ]
