# Generated by Django 5.2.6 on 2025-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_availableproject_about_availableproject_about_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='is_open_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='source_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
