# Generated by Django 5.2.6 on 2025-09-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_availableproject_is_open_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of source code downloads'),
        ),
    ]
