# Generated by Django 5.2.6 on 2025-09-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_availableproject_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontainer',
            name='have_main_domain',
            field=models.BooleanField(default=False),
        ),
    ]
