# Generated by Django 5.2.6 on 2025-09-25 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectcontainer_have_main_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentDBConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(help_text='POSTGRES_DB', max_length=255)),
                ('db_user', models.CharField(blank=True, help_text='POSTGRES_USER', max_length=255, null=True)),
                ('db_password', models.CharField(blank=True, help_text='POSTGRES_PASS', max_length=255, null=True)),
                ('db_host', models.CharField(blank=True, help_text='POSTGRES_HOST', max_length=255, null=True)),
                ('db_port', models.PositiveIntegerField(blank=True, help_text='POSTGRES_PORT', null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='db_config', to='projects.availableproject')),
            ],
        ),
    ]
