# Generated by Django 5.2.6 on 2025-09-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_deploymentdbconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeploymentDBConfig',
            new_name='ProjectDBConfig',
        ),
    ]
