# Generated by Django 5.2.6 on 2025-09-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_rename_deploymentdbconfig_projectdbconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdbconfig',
            name='db_host',
        ),
        migrations.RemoveField(
            model_name='projectdbconfig',
            name='db_port',
        ),
    ]
