# Generated by Django 5.2.6 on 2025-09-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_remove_projectdbconfig_db_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdbconfig',
            name='db_port',
            field=models.PositiveIntegerField(blank=True, help_text='POSTGRES_PORT', null=True),
        ),
    ]
