# Generated by Django 5.2.6 on 2025-09-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projectdbconfig_db_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='description_ro',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
