# Generated by Django 5.2.6 on 2025-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_availableproject_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontainer',
            name='healthcheck',
            field=models.JSONField(blank=True, default=dict, help_text='\n            {\n                "test": ["CMD-SHELL", "pg_isready -U user"],\n                "interval": 5000000000,  # 5 ثواني بالنانoseconds\n                "retries": 10,\n                "timeout": 3000000000  # 3 ثواني\n            }\n        ', null=True),
        ),
    ]
