# Generated by Django 5.2.6 on 2025-09-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_projectcontainer_healthcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='docker_compose_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
