# Generated by Django 5.2.6 on 2025-09-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_availableproject_docker_compose_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='which_service_has_main_domain',
            field=models.CharField(blank=True, help_text='enter service name from docker compose template', max_length=50, null=True),
        ),
    ]
