# Generated by Django 5.2.6 on 2025-09-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_availableproject_which_service_has_main_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcontainer',
            name='command',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='default_port',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='docker_image_name',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='entrypoint',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='env_vars',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='have_main_domain',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='healthcheck',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='networks',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='privileged',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='restart_policy',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='script_run_after_install',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='projectcontainer',
            name='working_dir',
        ),
        migrations.AddField(
            model_name='projectcontainer',
            name='service_name',
            field=models.CharField(help_text='service name in project docker compose template, for example=wordpress, db', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='availableproject',
            name='which_service_has_main_domain',
            field=models.CharField(blank=True, help_text='enter service name from docker compose template, for example=wordpress, db', max_length=50, null=True),
        ),
    ]
