# Generated by Django 5.2.6 on 2025-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_remove_projectcontainer_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdbconfig',
            name='service_name',
            field=models.CharField(help_text='service name in project docker compose template, for example=wordpress, db', max_length=50, null=True),
        ),
    ]
