# Generated by Django 5.2.6 on 2025-10-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_projectdbconfig_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableproject',
            name='docker_compose_template',
            field=models.TextField(blank=True, help_text='\n                                            {container.<service_name>.<field>}\n                                            {deployment.<field>}\n                                            {dc.<service_name>.<field>}\n                                            {uuid.mydb.16}\n                                            {uuid.wordpress.8}\n                                            ', null=True),
        ),
    ]
