# Generated by Django 5.2.6 on 2025-10-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_alter_availableproject_docker_compose_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproject',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='name_he',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='availableproject',
            name='name_ro',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Name'),
        ),
    ]
