# Generated by Django 4.2.16 on 2025-09-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ram', models.IntegerField(help_text='RAM بالـ MB')),
                ('storage', models.IntegerField(help_text='Storage بالـ GB')),
                ('cpu', models.DecimalField(decimal_places=1, help_text='عدد الأنوية أو النسبة', max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
