# Generated by Django 4.2.16 on 2025-09-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='storage',
            field=models.IntegerField(help_text='Storage بالـ mb'),
        ),
    ]
