# Generated by Django 4.2.16 on 2025-09-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='billing_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي')], default='monthly', help_text='نوع الاشتراك', max_length=10),
        ),
    ]
