# Generated by Django 4.2.16 on 2025-09-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('deployments', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='Theem',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], max_length=255, null=True, verbose_name='الثيم'),
        ),
        migrations.AddField(
            model_name='plan',
            name='database',
            field=models.CharField(choices=[('sqlite', 'SQLite'), ('postgresql', 'PostgreSQL')], max_length=255, null=True, verbose_name='قاعدة البيانات'),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('premium', 'Premium'), ('pro', 'PRO'), ('basic', 'Basic')], max_length=255, null=True, verbose_name='نو الاشتراك'),
        ),
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.availableproject'),
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deployments.deployment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
        ),
    ]
