# Generated by Django 4.2.16 on 2025-09-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectreview'),
        ('plans', '0002_alter_plan_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.availableproject'),
        ),
    ]
