# Generated by Django 4.2.16 on 2025-09-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_billing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='billing_type',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='Theem',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('success', 'success'), ('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('light', 'light'), ('dark', 'dark')], max_length=255, null=True, verbose_name='الثيم'),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('premium', 'Premium'), ('pro', 'PRO'), ('basic', 'Basic')], max_length=255, null=True, verbose_name='نو الاشتراك'),
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
