# Generated by Django 4.2.16 on 2025-09-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_plan_billing_type_remove_plan_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='database',
            field=models.CharField(choices=[('sqlite', 'SQLite'), ('postgresql', 'PostgreSQL')], max_length=255, null=True, verbose_name='قاعدة البيانات'),
        ),
    ]
