# Generated by Django 4.2.16 on 2025-09-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='expires_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='started_at',
            new_name='start_date',
        ),
    ]
