# Generated by Django 4.2.16 on 2025-09-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_availableproject_media_folder_path'),
        ('plans', '0006_rename_expires_at_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.availableproject'),
        ),
    ]
