# Generated by Django 4.2.16 on 2025-09-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Phone Number')),
                ('project_title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('project_description', models.TextField(verbose_name='Project Description')),
                ('similar_websites', models.TextField(blank=True, verbose_name='Examples of similar websites')),
                ('expected_budget', models.TextField(blank=True, max_length=100, verbose_name='Expected budget')),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeToUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
            ],
        ),
    ]
