# Generated by Django 4.2.16 on 2025-09-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Service Title')),
                ('sub_title', models.TextField(verbose_name='Subtitle')),
                ('service', models.CharField(choices=[('1', 'Patient Management'), ('2', 'School Management'), ('3', 'HR Management')], max_length=254, verbose_name='Service')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Service Model',
                'verbose_name_plural': 'Service Models',
            },
        ),
        migrations.CreateModel(
            name='UserServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=254, null=True, verbose_name='Project Name')),
                ('progress', models.CharField(choices=[('1', 'Create Project'), ('2', 'Choose Plan'), ('3', 'Project Settings'), ('4', 'Complited')], max_length=254, null=True, verbose_name='Progress')),
                ('service_subscription_id', models.CharField(max_length=254, null=True, verbose_name='Service Subscription ID')),
                ('service_user_id', models.CharField(max_length=254, null=True, verbose_name='Service User ID')),
                ('service_subscription_date', models.CharField(max_length=254, null=True, verbose_name='Service Subscription Date')),
                ('plan_scope', models.CharField(choices=[('1', 'Monthly'), ('2', 'Yearly')], max_length=254, null=True, verbose_name='Plan Scope')),
                ('system_port', models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='system_port')),
                ('subdomain', models.CharField(blank=True, max_length=254, null=True, verbose_name='Subdomain')),
                ('system_progress', models.CharField(choices=[('1', 'Pending'), ('2', 'Building'), ('3', 'Complited'), ('4', 'Failed')], default='1', max_length=254, null=True, verbose_name='System Progress')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.servicesmodel', verbose_name='Service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Service Model',
                'verbose_name_plural': 'User Service Models',
            },
        ),
    ]
