# Generated by Django 4.2.16 on 2024-09-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicemodel',
            name='project_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
