# Generated by Django 4.2.16 on 2024-09-23 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userservicemodel_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicemodel',
            name='progress',
            field=models.CharField(choices=[('1', 'Patient Management')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.servicesmodel'),
        ),
    ]
