# Generated by Django 4.2.16 on 2024-09-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_userservicemodel_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='progress',
            field=models.CharField(choices=[('1', 'Create Project'), ('2', 'Choose Plan'), ('3', 'Project Settings'), ('4', 'Done')], max_length=254, null=True),
        ),
    ]
