# Generated by Django 4.2.16 on 2024-09-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userservicemodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicemodel',
            name='progress_paid_plan_id',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
