# Generated by Django 4.2.16 on 2024-09-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userservicemodel_progress_paid_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicemodel',
            name='progress_paid_plan_scope',
            field=models.CharField(choices=[('1', 'Monthly'), ('2', 'Yearly')], max_length=254, null=True),
        ),
    ]
