# Generated by Django 4.2.16 on 2024-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_userservicemodel_progress_paid_plan_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicemodel',
            name='service_subscription_id',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userservicemodel',
            name='service_user_id',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
