# Generated by Django 4.2.16 on 2024-09-24 13:11

import dashboard.libs
from django.db import migrations, models
import django.db.models.deletion

import dashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_userservicemodel_service_subscription_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePaymentOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=254, null=True)),
                ('progress_paid_plan_scope', models.CharField(choices=[('1', 'Monthly'), ('2', 'Yearly')], max_length=254, null=True)),
                ('orderID', models.CharField(default='', max_length=250, null=True, verbose_name='الاسم الثلاثي')),
                ('transactionNo', models.CharField(max_length=250, null=True)),
                ('is_buyed', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
                ('UserService', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.userservicemodel')),
            ],
        ),
    ]
