# Generated by Django 4.2.16 on 2024-09-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_servicepaymentordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepaymentordermodel',
            old_name='UserService',
            new_name='user_service',
        ),
    ]
