# Generated by Django 4.2.16 on 2024-09-24 21:27

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_servicepaymentordermodel_is_buyed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepaymentordermodel',
            name='order_secret',
            field=models.CharField(default=dashboard.models.payOrderSecretCodeGen, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='progress',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Complited'), ('3', 'Cancelled')], default='1', max_length=254, null=True),
        ),
    ]
