# Generated by Django 4.2.16 on 2024-09-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_servicepaymentordermodel_order_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservicemodel',
            name='progress_paid_plan_id',
        ),
        migrations.RemoveField(
            model_name='userservicemodel',
            name='progress_paid_plan_scope',
        ),
    ]
