# Generated by Django 4.2.16 on 2024-09-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_userservicemodel_progress_paid_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicemodel',
            name='plan_scope',
            field=models.CharField(choices=[('1', 'Monthly'), ('2', 'Yearly')], max_length=254, null=True),
        ),
    ]
