# Generated by Django 4.2.16 on 2024-09-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_userservicemodel_plan_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='progress',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Paid'), ('3', 'Complited'), ('4', 'Cancelled')], default='1', max_length=254, null=True),
        ),
    ]
