# Generated by Django 4.2.16 on 2024-09-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_servicepaymentordermodel_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicemodel',
            name='service_subscription_date',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
