# Generated by Django 4.2.16 on 2025-02-21 11:53

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_alter_servicesmodel_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepaymentordermodel',
            options={'verbose_name': 'Service Payment Order Model', 'verbose_name_plural': 'Service Payment Order Models'},
        ),
        migrations.AlterModelOptions(
            name='servicesmodel',
            options={'verbose_name': 'Service Model', 'verbose_name_plural': 'Service Models'},
        ),
        migrations.AlterModelOptions(
            name='userservicemodel',
            options={'verbose_name': 'User Service Model', 'verbose_name_plural': 'User Service Models'},
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='orderID',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='order_secret',
            field=models.CharField(default=dashboard.models.payOrderSecretCodeGen, max_length=254, null=True, verbose_name='Order Secret Code'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='progress',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Paid'), ('3', 'Complited'), ('4', 'Cancelled')], default='1', max_length=254, null=True, verbose_name='Order Progress'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='progress_paid_plan_scope',
            field=models.CharField(choices=[('1', 'Monthly'), ('2', 'Yearly')], max_length=254, null=True, verbose_name='Paid Plan Scope'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='subscription_id',
            field=models.CharField(max_length=254, null=True, verbose_name='Subscription ID'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='transactionNo',
            field=models.CharField(max_length=250, null=True, verbose_name='Transaction Number'),
        ),
        migrations.AlterField(
            model_name='servicepaymentordermodel',
            name='user_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.userservicemodel', verbose_name='User Service'),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='service',
            field=models.CharField(choices=[('1', 'Patient Management'), ('2', 'School Management'), ('3', 'HR Management')], max_length=254, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='sub_title',
            field=models.TextField(verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='title',
            field=models.CharField(max_length=254, verbose_name='Service Title'),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='plan_scope',
            field=models.CharField(choices=[('1', 'Monthly'), ('2', 'Yearly')], max_length=254, null=True, verbose_name='Plan Scope'),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='progress',
            field=models.CharField(choices=[('1', 'Create Project'), ('2', 'Choose Plan'), ('3', 'Project Settings'), ('4', 'Complited')], max_length=254, null=True, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='project_name',
            field=models.CharField(max_length=254, null=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.servicesmodel', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='service_subscription_date',
            field=models.CharField(max_length=254, null=True, verbose_name='Service Subscription Date'),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='service_subscription_id',
            field=models.CharField(max_length=254, null=True, verbose_name='Service Subscription ID'),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='service_user_id',
            field=models.CharField(max_length=254, null=True, verbose_name='Service User ID'),
        ),
        migrations.AlterField(
            model_name='userservicemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
