# Generated by Django 4.2.16 on 2025-03-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_servicepaymentordermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservicemodel',
            name='subdomain',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Subdomain'),
        ),
        migrations.AddField(
            model_name='userservicemodel',
            name='system_port',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='system_port'),
        ),
        migrations.AddField(
            model_name='userservicemodel',
            name='system_progress',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Building'), ('3', 'Complited'), ('4', 'Failed')], default='1', max_length=254, null=True, verbose_name='System Progress'),
        ),
    ]
