# Generated by Django 4.2.16 on 2025-09-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_userservicemodel_subdomain_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePaymentOrderModel',
        ),
    ]
