# Generated by Django 4.2.16 on 2024-09-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img_base64',
            field=models.TextField(null=True),
        ),
    ]
