# Generated by Django 4.2.16 on 2024-09-25 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_userprofile_img_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('creation_date', models.DateTimeField(null=True, verbose_name='تاريخ الانشاء')),
                ('reaed_users', models.ManyToManyField(related_name='reaed_users', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ManyToManyField(related_name='noti_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
