# Generated by Django 4.2.16 on 2025-09-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('progress', models.IntegerField(choices=[(1, 'Create Project'), (2, 'Billing'), (3, 'Deploying'), (4, 'Completed'), (5, 'Failed')], null=True)),
                ('status', models.IntegerField(choices=[(1, 'Stopped'), (2, 'Running'), (3, 'Undefined')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('used_ram', models.PositiveIntegerField(blank=True, help_text='RAM used in MB', null=True)),
                ('used_storage', models.PositiveIntegerField(blank=True, help_text='Storage used in GB', null=True)),
                ('used_cpu', models.DecimalField(blank=True, decimal_places=1, help_text='CPU cores used', max_digits=3, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.availableproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('env_vars', models.JSONField(blank=True, default=dict)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Running'), (3, 'Error')], default=1)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='deployments.deployment')),
                ('project_container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectcontainer')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentContainerVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Path on container/server', max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='deployments.deploymentcontainer')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentContainerEnvVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envs', to='deployments.deploymentcontainer')),
                ('var', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.envvar')),
            ],
        ),
    ]
