# Generated by Django 4.2.16 on 2025-09-13 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('container_name', models.CharField(blank=True, max_length=255, null=True)),
                ('volume_media', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('progress', models.IntegerField(choices=[(1, 'Create Project'), (2, 'Billing'), (3, 'Deploying'), (4, 'Completed'), (5, 'Failed')], null=True, verbose_name='Progress')),
                ('status', models.IntegerField(choices=[(1, 'Stopped'), (2, 'Running'), (3, 'Undefined')], null=True, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True)),
                ('used_ram', models.IntegerField(blank=True, help_text='RAM used in MB', null=True)),
                ('used_storage', models.IntegerField(blank=True, help_text='Storage used in GB', null=True)),
                ('used_cpu', models.DecimalField(blank=True, decimal_places=1, help_text='CPU cores used', max_digits=3, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.availableproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentEnvVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.deployment')),
                ('var_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.envvarmodel')),
            ],
        ),
    ]
