# Generated by Django 4.2.16 on 2025-09-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='progress',
            field=models.CharField(choices=[('1', 'Create Project'), ('2', 'Billing'), ('3', 'Complited')], max_length=254, null=True, verbose_name='Progress'),
        ),
    ]
