# Generated by Django 4.2.16 on 2025-09-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_envvarstitle_project_container_and_more'),
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deploymentcontainerenvvar',
            unique_together={('container', 'var')},
        ),
    ]
