# Generated by Django 4.2.16 on 2025-09-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectcontainer_env_vars'),
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentContainerEnvVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deploymentcontainer',
            name='project_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectcontainer'),
        ),
        migrations.DeleteModel(
            name='DeploymentEnvVar',
        ),
        migrations.AddField(
            model_name='deploymentcontainerenvvar',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envs', to='deployments.deploymentcontainer'),
        ),
        migrations.AddField(
            model_name='deploymentcontainerenvvar',
            name='var',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.envvar'),
        ),
    ]
