# Generated by Django 4.2.16 on 2025-09-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_alter_deploymentcontainerenvvar_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploymentcontainerenvvar',
            options={'ordering': ['var__sort_index']},
        ),
    ]
