# Generated by Django 4.2.16 on 2025-09-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_deploymentcontainerenvvar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='frontend_domain',
        ),
        migrations.AddField(
            model_name='deploymentcontainer',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
