# Generated by Django 4.2.16 on 2025-09-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_deployment_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('1', 'Stoped'), ('2', 'Runing'), ('3', 'Undefined')], max_length=254, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='progress',
            field=models.CharField(choices=[('1', 'Create Project'), ('2', 'Billing'), ('3', 'Deploying'), ('4', 'Complited'), ('5', 'Failed')], max_length=254, null=True, verbose_name='Progress'),
        ),
    ]
