# Generated by Django 4.2.16 on 2025-09-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_alter_deploymentcontainerenvvar_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentcontainer',
            name='env_vars',
        ),
        migrations.RemoveField(
            model_name='deploymentcontainer',
            name='port',
        ),
    ]
