# Generated by Django 4.2.16 on 2025-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_remove_deployment_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='container_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
