# Generated by Django 4.2.16 on 2025-09-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_deployment_status_alter_deployment_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='container_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='used_cpu',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='CPU cores used', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='used_ram',
            field=models.IntegerField(blank=True, help_text='RAM used in MB', null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='used_storage',
            field=models.IntegerField(blank=True, help_text='Storage used in GB', null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='version',
            field=models.CharField(default='1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='progress',
            field=models.IntegerField(choices=[(1, 'Create Project'), (2, 'Billing'), (3, 'Deploying'), (4, 'Completed'), (5, 'Failed')], null=True, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Stopped'), (2, 'Running'), (3, 'Undefined')], null=True, verbose_name='Status'),
        ),
    ]
