# Generated by Django 4.2.16 on 2025-09-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_deployment_container_id_deployment_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
