# Generated by Django 4.2.16 on 2025-09-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_deployment_container_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='container_name',
        ),
    ]
