# Generated by Django 5.2.6 on 2025-09-24 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_remove_deploymentcontainer_env_vars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', 'Full Project (volumes + db)'), ('db', 'Database Only')], default='full', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Path to backup archive (tar.gz)', max_length=512, null=True)),
                ('size_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('restored', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('db_version', models.CharField(blank=True, max_length=50, null=True)),
                ('project_version', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_backend', models.CharField(default='local', help_text='local, s3, gcs...', max_length=50)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='deployments.deployment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
