# Generated by Django 5.2.6 on 2025-09-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_deploymentbackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentbackup',
            name='db_version',
        ),
        migrations.RemoveField(
            model_name='deploymentbackup',
            name='project_version',
        ),
        migrations.RemoveField(
            model_name='deploymentbackup',
            name='storage_backend',
        ),
        migrations.AlterField(
            model_name='deploymentbackup',
            name='file_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
