# Generated by Django 4.2.16 on 2025-09-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_deployment_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='container_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
