# Generated by Django 5.2.6 on 2025-09-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_remove_deploymentbackup_db_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentbackup',
            name='backup_summary',
            field=models.CharField(blank=True, help_text='Summary of what was backed up', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deploymentbackup',
            name='backup_type',
            field=models.CharField(choices=[('full', 'Full (Files + Database)'), ('files', 'Files Only'), ('db', 'Database Only')], default='full', max_length=10),
        ),
    ]
