# Generated by Django 4.2.16 on 2025-09-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_deployment_container_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='volume_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
