# Generated by Django 5.2.6 on 2025-09-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_deploymentbackup_backup_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentcontainer',
            name='project_container',
        ),
        migrations.AddField(
            model_name='deploymentcontainer',
            name='pc_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
