# Generated by Django 4.2.16 on 2025-09-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_deployment_volume_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='volume_name',
            new_name='volume_media',
        ),
    ]
