# Generated by Django 5.2.6 on 2025-09-29 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0008_remove_deploymentcontainer_project_container_and_more'),
        ('projects', '0029_availableproject_docker_compose_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentcontainer',
            name='project_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectcontainer'),
        ),
    ]
