# Generated by Django 4.2.16 on 2025-09-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0008_rename_volume_name_deployment_volume_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='container_id',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='subscription_end',
        ),
    ]
