# Generated by Django 4.2.16 on 2025-09-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_actionmodel_command_and_more'),
        ('deployments', '0009_remove_deployment_container_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentEnvVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.deployment')),
                ('var_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.envvarmodel')),
            ],
        ),
    ]
