# Generated by Django 5.2.6 on 2025-09-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0009_deploymentcontainer_project_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployment_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deploymentcontainer',
            name='dc_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
