# Generated by Django 5.2.6 on 2025-09-29 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0010_deployment_deployment_name_and_more'),
        ('projects', '0031_remove_projectcontainer_command_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploymentcontainer',
            old_name='pc_name',
            new_name='service_name',
        ),
        migrations.AlterField(
            model_name='deploymentcontainer',
            name='project_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectcontainer'),
        ),
    ]
