# Generated by Django 5.2.6 on 2025-10-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0011_rename_pc_name_deploymentcontainer_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='compose_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
