# Generated by Django 5.2.6 on 2025-10-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0012_deployment_compose_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='_uuid_cache',
            field=models.JSONField(default=dict),
        ),
    ]
