# Generated by Django 5.2.6 on 2025-10-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0013_deployment__uuid_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='_uuid_cache',
        ),
        migrations.AddField(
            model_name='deployment',
            name='uuid_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
