version: '3.9'
services:
  db_81_app:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: db-81_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: strongpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
    - C:\containers\mnt\vol_81\db-81_var_lib_mysql:/var/lib/mysql
    container_name: db-81
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024m
    networks:
    - deploy_network
  wordpress_81_app:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_81_app:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: strongpassword
      WORDPRESS_DB_NAME: db-81_db
    depends_on:
    - db_81_app
    volumes:
    - C:\containers\mnt\vol_81\wordpress-81_var_www_html:/var/www/html
    labels:
      traefik.enable: 'true'
      traefik.http.routers.wordpress-81.rule: Host(`wordpress-81.softmsg.com`)
      traefik.http.routers.wordpress-81.entrypoints: web,websecure
      traefik.http.routers.wordpress-81.tls.certresolver: myresolver
      traefik.http.services.wordpress-81.loadbalancer.server.port: 80
    container_name: wordpress-81
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024m
    networks:
    - deploy_network
volumes:
  db-81_var_lib_mysql: null
  wordpress-81_var_www_html: null
networks:
  deploy_network:
    external: true
