version: '3.9'
services:
  db_82_app:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: db-82_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: c768c77d4ba04b5f
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
    - C:\containers\mnt\vol_82\db-82_var_lib_mysql:/var/lib/mysql
    container_name: db-82
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024m
    networks:
    - deploy_network
  wordpress_82_app:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_82_app:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD:
        container.db.environment.MYSQL_PASSWORD: null
      WORDPRESS_DB_NAME: db-82_db
    depends_on:
    - db_82_app
    volumes:
    - C:\containers\mnt\vol_82\wordpress-82_var_www_html:/var/www/html
    labels:
      traefik.enable: 'true'
      traefik.http.routers.wordpress-82.rule: Host(`wordpress-82.softmsg.com`)
      traefik.http.routers.wordpress-82.entrypoints: web,websecure
      traefik.http.routers.wordpress-82.tls.certresolver: myresolver
      traefik.http.services.wordpress-82.loadbalancer.server.port: 80
    container_name: wordpress-82
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024m
    networks:
    - deploy_network
volumes:
  db-82_var_lib_mysql: null
  wordpress-82_var_www_html: null
networks:
  deploy_network:
    external: true
