# Generated by Django 4.2.16 on 2025-09-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0009_remove_deployment_container_id_and_more'),
        ('plans', '0003_remove_plan_billing_type_remove_plan_price_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deployments.deployment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
        ),
        migrations.DeleteModel(
            name='HRSubscriptionsModel',
        ),
    ]
