# Generated by Django 4.2.16 on 2025-09-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_delete_hrsubscriptionsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
