# Generated by Django 4.2.16 on 2025-09-13 20:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocsServiceSectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Section Name')),
                ('name_ar', models.CharField(max_length=254, null=True, verbose_name='Section Name')),
                ('name_en', models.CharField(max_length=254, null=True, verbose_name='Section Name')),
                ('name_de', models.CharField(max_length=254, null=True, verbose_name='Section Name')),
                ('name_he', models.CharField(max_length=254, null=True, verbose_name='Section Name')),
                ('name_ro', models.CharField(max_length=254, null=True, verbose_name='Section Name')),
                ('desc', models.TextField(verbose_name='Section Description')),
                ('is_enabled', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('ordering', models.CharField(default='0', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DocsServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Service Name')),
                ('name_ar', models.CharField(max_length=254, null=True, verbose_name='Service Name')),
                ('name_en', models.CharField(max_length=254, null=True, verbose_name='Service Name')),
                ('name_de', models.CharField(max_length=254, null=True, verbose_name='Service Name')),
                ('name_he', models.CharField(max_length=254, null=True, verbose_name='Service Name')),
                ('name_ro', models.CharField(max_length=254, null=True, verbose_name='Service Name')),
                ('desc', models.TextField(verbose_name='Service Description')),
                ('is_enabled', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('ordering', models.CharField(default='0', max_length=254)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='SectionContentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Content Name')),
                ('name_ar', models.CharField(max_length=254, null=True, verbose_name='Content Name')),
                ('name_en', models.CharField(max_length=254, null=True, verbose_name='Content Name')),
                ('name_de', models.CharField(max_length=254, null=True, verbose_name='Content Name')),
                ('name_he', models.CharField(max_length=254, null=True, verbose_name='Content Name')),
                ('name_ro', models.CharField(max_length=254, null=True, verbose_name='Content Name')),
                ('desc', models.TextField(verbose_name='Content Description')),
                ('desc_ar', models.TextField(null=True, verbose_name='Content Description')),
                ('desc_en', models.TextField(null=True, verbose_name='Content Description')),
                ('desc_de', models.TextField(null=True, verbose_name='Content Description')),
                ('desc_he', models.TextField(null=True, verbose_name='Content Description')),
                ('desc_ro', models.TextField(null=True, verbose_name='Content Description')),
                ('content', tinymce.models.HTMLField()),
                ('content_ar', tinymce.models.HTMLField(null=True)),
                ('content_en', tinymce.models.HTMLField(null=True)),
                ('content_de', tinymce.models.HTMLField(null=True)),
                ('content_he', tinymce.models.HTMLField(null=True)),
                ('content_ro', tinymce.models.HTMLField(null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('ordering', models.CharField(default='0', max_length=254)),
                ('is_default_selected', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.docsservicesectionsmodel')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.AddField(
            model_name='docsservicesectionsmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.docsservicesmodel'),
        ),
    ]
