# Generated by Django 4.2.16 on 2024-10-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsservicesectionsmodel',
            name='ordering',
            field=models.CharField(default='0', max_length=254),
        ),
        migrations.AddField(
            model_name='docsservicesmodel',
            name='ordering',
            field=models.CharField(default='0', max_length=254),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='is_default_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='ordering',
            field=models.CharField(default='0', max_length=254),
        ),
    ]
