# Generated by Django 4.2.16 on 2025-09-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_projectcontainer_env_vars'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsservicesmodel',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.availableproject', verbose_name='Project'),
        ),
    ]
