# Generated by Django 4.2.16 on 2025-09-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_availableproject_installs'),
        ('resources', '0002_docsservicesmodel_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docsservicesectionsmodel',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterField(
            model_name='docsservicesectionsmodel',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='docsservicesectionsmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resources.docsservicesmodel'),
        ),
        migrations.AlterField(
            model_name='docsservicesmodel',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='docsservicesmodel',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs_services', to='projects.availableproject'),
        ),
        migrations.AlterField(
            model_name='sectioncontentsmodel',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sectioncontentsmodel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='resources.docsservicesectionsmodel'),
        ),
    ]
