# Generated by Django 4.2.16 on 2025-02-21 11:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_docsservicesectionsmodel_ordering_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docsservicesmodel',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='sectioncontentsmodel',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='docsservicesectionsmodel',
            name='name_ar',
            field=models.CharField(max_length=254, null=True, verbose_name='Section Name'),
        ),
        migrations.AddField(
            model_name='docsservicesectionsmodel',
            name='name_de',
            field=models.CharField(max_length=254, null=True, verbose_name='Section Name'),
        ),
        migrations.AddField(
            model_name='docsservicesectionsmodel',
            name='name_en',
            field=models.CharField(max_length=254, null=True, verbose_name='Section Name'),
        ),
        migrations.AddField(
            model_name='docsservicesectionsmodel',
            name='name_he',
            field=models.CharField(max_length=254, null=True, verbose_name='Section Name'),
        ),
        migrations.AddField(
            model_name='docsservicesectionsmodel',
            name='name_ro',
            field=models.CharField(max_length=254, null=True, verbose_name='Section Name'),
        ),
        migrations.AddField(
            model_name='docsservicesmodel',
            name='name_ar',
            field=models.CharField(max_length=254, null=True, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='docsservicesmodel',
            name='name_de',
            field=models.CharField(max_length=254, null=True, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='docsservicesmodel',
            name='name_en',
            field=models.CharField(max_length=254, null=True, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='docsservicesmodel',
            name='name_he',
            field=models.CharField(max_length=254, null=True, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='docsservicesmodel',
            name='name_ro',
            field=models.CharField(max_length=254, null=True, verbose_name='Service Name'),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='content_ar',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='content_de',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='content_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='content_he',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='content_ro',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='desc_ar',
            field=models.TextField(null=True, verbose_name='Content Description'),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='desc_de',
            field=models.TextField(null=True, verbose_name='Content Description'),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='Content Description'),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='desc_he',
            field=models.TextField(null=True, verbose_name='Content Description'),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='desc_ro',
            field=models.TextField(null=True, verbose_name='Content Description'),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='name_ar',
            field=models.CharField(max_length=254, null=True, verbose_name='Content Name'),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='name_de',
            field=models.CharField(max_length=254, null=True, verbose_name='Content Name'),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='name_en',
            field=models.CharField(max_length=254, null=True, verbose_name='Content Name'),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='name_he',
            field=models.CharField(max_length=254, null=True, verbose_name='Content Name'),
        ),
        migrations.AddField(
            model_name='sectioncontentsmodel',
            name='name_ro',
            field=models.CharField(max_length=254, null=True, verbose_name='Content Name'),
        ),
    ]
