# Generated by Django 4.2.16 on 2025-09-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_docsservicesectionsmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsservicesectionsmodel',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='docsservicesectionsmodel',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='docsservicesectionsmodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='docsservicesectionsmodel',
            name='name_he',
        ),
        migrations.RemoveField(
            model_name='docsservicesectionsmodel',
            name='name_ro',
        ),
        migrations.RemoveField(
            model_name='docsservicesmodel',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='docsservicesmodel',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='docsservicesmodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='docsservicesmodel',
            name='name_he',
        ),
        migrations.RemoveField(
            model_name='docsservicesmodel',
            name='name_ro',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='content_ar',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='content_he',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='content_ro',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='desc_ar',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='desc_de',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='desc_he',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='name_he',
        ),
        migrations.RemoveField(
            model_name='sectioncontentsmodel',
            name='name_ro',
        ),
    ]
