# Generated by Django 5.2.6 on 2025-09-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_category_options_action_label_ar_and_more'),
        ('resources', '0005_docsservicesectionsmodel_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsservicesmodel',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='projects.availableproject'),
        ),
    ]
